(* TEST
 readonly_files = "int32_u_array.ml"
 modules = "${readonly_files}"
 * flambda2
 ** bytecode
   flags = "-extension layouts_alpha"
 ** bytecode
   flags = "-extension layouts_beta"
 ** native
   flags = "-extension layouts_alpha"
 ** native
   flags = "-extension layouts_beta"
*)

(* Do not edit this file directly.
   Change "*.ml.template" files and run "gen.py" instead. *)

open Printf

module type S = sig
  type t
  val length : t -> int
  val get : t -> int -> int32
  val set : t -> int -> int32 -> unit
  val make : int -> int32 -> t
  val init : int -> (int -> int32) -> t
  val append : t -> t -> t
  val concat : t list -> t
  val sub : t -> int -> int -> t
  val copy : t -> t
  val fill : t -> int -> int -> int32 -> unit
  val blit : t -> int -> t -> int -> int -> unit
  val to_list : t -> int32 list
  val of_list : int32 list -> t
  val iter : (int32 -> unit) -> t -> unit
  val iteri : (int -> int32 -> unit) -> t -> unit
  val map : (int32 -> int32) -> t -> t
  val mapi : (int -> int32 -> int32) -> t -> t
  val fold_left : ('a -> int32 -> 'a) -> 'a -> t -> 'a
  val fold_right : (int32 -> 'a -> 'a) -> t -> 'a -> 'a
  val iter2 : (int32 -> int32 -> unit) -> t -> t -> unit
  val map2 : (int32 -> int32 -> int32) -> t -> t -> t
  val for_all : (int32 -> bool) -> t -> bool
  val exists : (int32 -> bool) -> t -> bool
  val mem : int32 -> t -> bool
  val sort : (int32 -> int32 -> int) -> t -> unit
  val stable_sort : (int32 -> int32 -> int) -> t -> unit
  val fast_sort : (int32 -> int32 -> int) -> t -> unit
  val to_seq : t -> int32 Seq.t
  val to_seqi : t -> (int * int32) Seq.t
  val of_seq : int32 Seq.t -> t
  val map_to_array : (int32 -> 'a) -> t -> 'a array
  val map_from_array : ('a -> int32) -> 'a array -> t
  val unsafe_get : t -> int -> int32
  val unsafe_set : t -> int -> int32 -> unit
  val equal : t -> t -> bool
  (* From Sys, rather than Float.Array *)
  val max_length : int
end

module Int32_array : S = struct
  include Stdlib.Array
  let map_to_array f a = map f a
  let map_from_array f a = map f a
  type t = int32 array
  let max_length = Sys.max_array_length
  let equal = for_all2 (fun x y -> x = y)
end

module Std_Int32_u_array = Int32_u_array
module Int32_u_array : S = struct
  include Int32_u_array

  module Int32_u = Stdlib__Int32_u

  let to_boxed = Int32_u.to_int32
  let of_boxed = Int32_u.of_int32

  type t = int32# array

  let empty () = make 0 (of_boxed 0l)
  let to_seq a =
    let rec aux i () =
      if i < length a
      then
        let x = unsafe_get a i in
        Seq.Cons (to_boxed x, aux (i+1))
      else Seq.Nil
    in
    aux 0

  let to_seqi a =
    let rec aux i () =
      if i < length a
      then
        let x = unsafe_get a i in
        Seq.Cons ((i,to_boxed x), aux (i+1))
      else Seq.Nil
    in
    aux 0

  let of_rev_list = function
      [] -> empty ()
    | hd::tl as l ->
      let len = List.length l in
      let a = make len (of_boxed hd) in
      let rec fill i = function
          [] -> a
        | hd::tl -> unsafe_set a i (of_boxed hd); fill (i-1) tl
      in
      fill (len-2) tl

  let of_seq i =
    let l = Seq.fold_left (fun acc x -> x::acc) [] i in
    of_rev_list l


  let to_list t = fold_right (fun f l -> (to_boxed f)::l) t []
  (* let res = ref [] in
   * iter (fun f -> res := (to_boxed f) :: !res);
   * List.rev res *)

  let of_list l =
    let len = List.length l in
    let res = create len #0l in
    List.iteri (fun idx f -> set res idx (of_boxed f)) l;
    res
  let max_length = Sys.max_array_length
  let get t idx = to_boxed (get t idx)
  let set t idx v = set t idx (of_boxed v)

  let make l f = make l (of_boxed f)
  let init l f = init l (fun i -> of_boxed (f i))
  let fill a ofs len v = fill a ofs len (of_boxed v)
  let iter f t = iter (fun v -> f (to_boxed v)) t
  let iteri f t = iteri (fun i v -> f i (to_boxed v)) t
  let map f t = map (fun v -> of_boxed (f (to_boxed v))) t
  let mapi f t = mapi (fun i v -> of_boxed (f i (to_boxed v))) t
  let fold_left f acc t = fold_left (fun acc v -> f acc (to_boxed v)) acc t
  let fold_right f t acc = fold_right (fun v acc -> f (to_boxed v) acc) t acc

  let iter2 f a b = iter2 (fun v1 v2 -> f (to_boxed v1) (to_boxed v2)) a b
  let map2 f a b = map2 (fun v1 v2 -> of_boxed (f (to_boxed v1) (to_boxed v2))) a b
  let for_all f t = for_all (fun v -> f (to_boxed v)) t
  let exists f t = exists (fun v -> f (to_boxed v)) t
  let mem v t = mem (of_boxed v) t
  let sort f t = sort (fun a b -> f (to_boxed a) (to_boxed b)) t
  let stable_sort f t = stable_sort (fun a b -> f (to_boxed a) (to_boxed b)) t
  let fast_sort f t = fast_sort (fun a b -> f (to_boxed a) (to_boxed b)) t

  let map_to_array f t =
    if length t = 0 then [||] else begin
      let res = Array.make (length t) (f (get t 0)) in
      iteri (fun idx v -> if idx > 0 then Array.set res idx (f v)) t;
      res
    end

  let map_from_array f a =
    if Array.length a = 0 then empty () else begin
      let res = make (Array.length a) (f (Array.get a 0)) in
      Array.iteri (fun idx v -> if idx > 0 then set res idx (f v)) a;
      res
    end

  let unsafe_get t idx = to_boxed (unsafe_get t idx)
  let unsafe_set t idx v = unsafe_set t idx (of_boxed v)
  let equal = for_all2 (fun x y -> to_boxed x = to_boxed y)
end


module Test (A : S) : sig end = struct

  (* auxiliary functions *)

  let module I = Int32 in
  let rec check_i_upto a i =
    if i >= 0 then begin
      assert (A.get a i = I.of_int i);
      check_i_upto a (i - 1);
    end
  in

  let check_i a = check_i_upto a (A.length a - 1) in

  let check_inval f arg =
    match f arg with
    | _ -> assert false
    | exception (Invalid_argument _) -> ()
    | exception _ -> assert false
  in

  (* [make] [set] [get] *)
  let a = A.make 1000 1l in
  for i = 0 to 499 do A.set a i (I.of_int i) done;
  let rec loop i =
    if i >= 0 then begin
      assert (A.get a i = (if i < 500 then I.of_int i else 1l));
      loop (i - 1);
    end
  in loop 999;
  check_inval (A.get a) (-1);
  check_inval (A.get a) (1000);
  check_inval (fun i -> A.set a i 1l) (-1);
  check_inval (fun i -> A.set a i 1l) 1000;
  check_inval (fun i -> A.make i 1l) (-1);
  check_inval (fun i -> A.make i 1l) (A.max_length + 1);

  let a = A.make 1001 1l in
  for i = 0 to 499 do A.set a i (I.of_int i) done;
  let rec loop i =
    if i >= 0 then begin
      assert (A.get a i = (if i < 500 then I.of_int i else 1l));
      loop (i - 1);
    end
  in loop 1000;
  check_inval (A.get a) (-1);
  check_inval (A.get a) (1001);
  check_inval (fun i -> A.set a i 1l) (-1);
  check_inval (fun i -> A.set a i 1l) 1001;

  (* [length] *)
  let test_length l = assert (l = (A.length (A.make l 1l))) in
  test_length 0;
  test_length 1;
  test_length 10;
  test_length 25;
  test_length 255;
  test_length 256;
  test_length 1000;
  test_length 1001;
  test_length 123456;

  (* [init] *)
  let a = A.init 1000 I.of_int in
  check_i a;
  let a = A.init 1001 I.of_int in
  check_i a;
  check_inval (fun i -> A.init i I.of_int) (-1);
  check_inval (fun i -> A.init i I.of_int) (A.max_length + 1);

  (* [append] *)
  let check m n =
    let a = A.init m I.of_int in
    let b = A.init n (fun x -> I.of_int (x + m)) in
    let c = A.append a b in
    assert (A.length c = (m + n));
    check_i c;
  in
  check 0 0;
  check 0 100;
  check 1 100;
  check 100 0;
  check 100 1;
  check 100 100;
  check 1000 1000;
  check 1000 1001;
  check 1001 1000;
  check 1001 1001;
  (* check_inval omitted *)

  (* [concat] *)
  let check l =
    let f (len, acc) n =
      (len + n, A.init n (fun i -> I.of_int (len + i)) :: acc)
    in
    let (total, ll) = List.fold_left f (0, []) l in
    let b = A.concat (List.rev ll) in
    assert (A.length b = total);
    check_i b;
  in
  check [0; 0; 0];
  check [1; 10; 100];
  check [10; 0];
  check [0];
  check [1000; 1000; 1000];
  check [];
  check [1001; 1000; 1000];
  check [1000; 1001; 1000];
  check [1000; 1000; 1001];
  check [1001; 1001; 1001];
  (* check_inval omitted *)

  (* [sub] *)
  let a = A.init 1000 (fun i -> I.of_int (i - 100)) in
  let b = A.sub a 100 200 in
  check_i b;
  assert (A.length b = 200);
  let b = A.sub a 1000 0 in
  check_i (A.sub a 1000 0);
  assert  (A.length b = 0);
  check_inval (A.sub a (-1)) 0;
  check_inval (A.sub a 0) (-1);
  check_inval (A.sub a 0) 1001;
  check_inval (A.sub a 1000) 1;

  let a = A.init 1001 (fun i -> I.of_int (i - 101)) in
  let b = A.sub a 101 199 in
  check_i b;
  assert (A.length b = 199);
  let b = A.sub a 1001 0 in
  check_i (A.sub a 1001 0);
  assert  (A.length b = 0);
  check_inval (A.sub a (-1)) 0;
  check_inval (A.sub a 0) (-1);
  check_inval (A.sub a 0) 1002;
  check_inval (A.sub a 1001) 1;

  (* [copy] *)
  let check len =
    let a = A.init len I.of_int in
    let b = A.copy a in
    check_i b;
    assert (A.length b = len);
  in
  check 0;
  check 1;
  check 128;
  check 1023;

  (* [blit] [fill] *)
  let test_blit_fill data initval ofs len =
    let a = A.of_list data in
    let b = A.make (List.length data) 1l in
    A.blit a 0 b 0 (A.length b);
    assert (A.equal a b);
    A.fill b ofs len initval;
    let rec check i = function
      | [] -> ()
      | hd :: tl ->
          assert (A.get b i = (if i >= ofs && i < ofs + len
                               then initval else hd));
          check (i + 1) tl;
    in
    check 0 data
  in
  test_blit_fill [1l;2l;5l;8l;-100l;2120000000l] 3l 3 2;
  let a = A.make 100 0l in
  check_inval (A.fill a (-1) 0) 1l;
  check_inval (A.fill a 0 (-1)) 1l;
  check_inval (A.fill a 0 101) 1l;
  check_inval (A.fill a 100 1) 1l;
  check_inval (A.fill a 101 0) 1l;
  check_inval (A.blit a (-1) a 0) 0;
  check_inval (A.blit a 0 a 0) (-1);
  check_inval (A.blit a 0 a 0) 101;
  check_inval (A.blit a 100 a 0) 1;
  check_inval (A.blit a 101 a 0) 0;
  check_inval (A.blit a 0 a (-1)) 0;
  check_inval (A.blit a 0 a 100) 1;
  check_inval (A.blit a 0 a 101) 0;
  let a = A.make 101 0l in
  check_inval (A.fill a (-1) 0) 1l;
  check_inval (A.fill a 0 (-1)) 1l;
  check_inval (A.fill a 0 102) 1l;
  check_inval (A.fill a 101 1) 1l;
  check_inval (A.fill a 102 0) 1l;
  check_inval (A.blit a (-1) a 0) 0;
  check_inval (A.blit a 0 a 0) (-1);
  check_inval (A.blit a 0 a 0) 102;
  check_inval (A.blit a 101 a 0) 1;
  check_inval (A.blit a 102 a 0) 0;
  check_inval (A.blit a 0 a (-1)) 0;
  check_inval (A.blit a 0 a 101) 1;
  check_inval (A.blit a 0 a 102) 0;
  let test_blit_overlap a ofs1 ofs2 len =
    let a = A.of_list a in
    let b = A.copy a in
    A.blit a ofs1 a ofs2 len;
    for i = 0 to len - 1 do
      assert (A.get b (ofs1 + i) = A.get a (ofs2 + i))
    done
  in
  test_blit_overlap [1l; 2l; 3l; 4l] 1 2 2;

  (* [to_list] [of_list] *)
  let a = A.init 1000 I.of_int in
  assert (A.equal a (A.of_list (A.to_list a)));
  let a = A.init 1001 I.of_int in
  assert (A.equal a (A.of_list (A.to_list a)));
  let a = A.init 0 I.of_int in
  assert (A.equal a (A.of_list (A.to_list a)));
  (* check_inval omitted *)

  (* [iter] *)
  let a = A.init 300 (I.of_int) in
  let r = ref 0l in
  A.iter (fun x -> assert (x = !r); r := I.add x 1l) a;
  A.iter (fun _ -> assert false) (A.make 0 0l);
  assert (!r = 300l);

  let a = A.init 301 (I.of_int) in
  let r = ref 0l in
  A.iter (fun x -> assert (x = !r); r := I.add x 1l) a;
  assert (!r = 301l);

  (* [iteri] *)
  let a = A.init 300 I.of_int in
  let r = ref 0 in
  let f i x =
    assert (i = !r);
    assert (x = I.of_int i);
    r := i + 1
  in
  A.iteri f a;
  A.iteri (fun _ _ -> assert false) (A.make 0 0l);
  assert (!r = 300);

  let a = A.init 301 I.of_int in
  let r = ref 0 in
  let f i x =
    assert (i = !r);
    assert (x = I.of_int i);
    r := i + 1
  in
  A.iteri f a;
  A.iteri (fun _ _ -> assert false) (A.make 0 0l);
  assert (!r = 301);

  (* [map], test result and order of evaluation *)
  let a = A.init 500 I.of_int in
  let r = ref 0l in
  let f x =
    assert (x = !r);
    r := I.add !r 1l;
    I.sub x 1l
  in
  let b = A.map f a in
  check_i (A.sub b 1 499);

  let a = A.init 501 I.of_int in
  let r = ref 0l in
  let f x =
    assert (x = !r);
    r := I.add !r 1l;
    I.sub x 1l
  in
  let b = A.map f a in
  check_i (A.sub b 1 500);

  (* [mapi], test result and order of evaluation *)
  let a = A.init 500 I.of_int in
  let r = ref 0l in
  let f i x =
    assert (x = I.of_int i);
    assert (x = !r);
    r := I.add !r 1l;
    I.sub x 1l
  in
  let b = A.mapi f a in
  check_i (A.sub b 1 499);

  let a = A.init 501 I.of_int in
  let r = ref 0l in
  let f i x =
    assert (x = I.of_int i);
    assert (x = !r);
    r := I.add !r 1l;
    I.sub x 1l
  in
  let b = A.mapi f a in
  check_i (A.sub b 1 500);

  (* [fold_left], test result and order of evaluation *)
  let a = A.init 500 I.of_int in
  let f acc x =
    assert (acc = x);
    I.add x 1l
  in
  let acc = A.fold_left f 0l a in
  assert (acc = 500l);

  let a = A.init 501 I.of_int in
  let acc = A.fold_left f 0l a in
  assert (acc = 501l);

  (* [fold_right], test result and order of evaluation *)
  let a = A.init 500 I.of_int in
  let f x acc =
    assert (x = I.sub acc 1l);
    x
  in
  let acc = A.fold_right f a 500l in
  assert (acc = 0l);

  let a = A.init 501 I.of_int in
  let acc = A.fold_right f a 501l in
  assert (acc = 0l);

  (* [iter2], test result and order of evaluation *)
  let a = A.init 123 I.of_int in
  let b = A.init 123 I.of_int in
  let r = ref 0l in
  let f x y =
    assert (x = !r);
    assert (y = !r);
    r := I.add!r 1l;
  in
  A.iter2 f a b;
  let c = A.make 456 0l in
  check_inval (A.iter2 (fun _ _ -> assert false) a) c;
  check_inval (A.iter2 (fun _ _ -> assert false) c) a;

  let a = A.init 124 I.of_int in
  let b = A.init 124 I.of_int in
  let r = ref 0l in
  let f x y =
    assert (x = !r);
    assert (y = !r);
    r := I.add !r 1l;
  in
  A.iter2 f a b;

  (* [map2], test result and order of evaluation *)
  let a = A.init 456 I.of_int in
  let b = A.init 456 (fun i -> I.(mul (of_int i) 2l)) in
  let r = ref 0l in
  let f x y =
    assert (x = !r);
    assert (y = I.mul !r 2l);
    r := I.add !r 1l;
    I.(neg (sub x y))
  in
  let c = A.map2 f a b in
  check_i c;
  let d = A.make 455 0l in
  check_inval (A.map2 (fun _ _ -> assert false) a) d;
  check_inval (A.map2 (fun _ _ -> assert false) d) a;

  let a = A.init 457 I.of_int in
  let b = A.init 457 (fun i -> I.(mul (of_int i) 2l)) in
  let r = ref 0l in
  let f x y =
    assert (x = !r);
    assert (y = I.mul !r 2l);
    r := I.add !r 1l;
    I.(neg (sub x y))
  in
  let c = A.map2 f a b in
  check_i c;

  (* [for_all], test result and order of evaluation *)
  let a = A.init 777 I.of_int in
  let r = ref 0l in
  let f x =
    assert (x = !r);
    r := I.add x 1l;
    true
  in
  assert (A.for_all f a);
  let f x = assert (x = 0l); false in
  assert (not (A.for_all f a));

  let a = A.init 778 I.of_int in
  let r = ref 0l in
  let f x =
    assert (x = !r);
    r := I.add x 1l;
    true
  in
  assert (A.for_all f a);
  let f x = assert (x = 0l); false in
  assert (not (A.for_all f a));

  (* [exists], test result and order of evaluation *)
  let a = A.init 777 I.of_int in
  let r = ref 0l in
  let f x =
    assert (x = !r);
    r := I.add x 1l;
    false
  in
  assert (not (A.exists f a));
  let f x = assert (x = 0l); true in
  assert (A.exists f a);

  let a = A.init 778 I.of_int in
  let r = ref 0l in
  let f x =
    assert (x = !r);
    r := I.add x 1l;
    false
  in
  assert (not (A.exists f a));
  let f x = assert (x = 0l); true in
  assert (A.exists f a);

  (* [mem] *)
  let a = A.init 7777 I.of_int in
  assert (A.mem 0l a);
  assert (A.mem 7776l a);
  assert (not (A.mem (-1l) a));
  assert (not (A.mem 7777l a));
  let check v =
    A.set a 1000 v;
    assert (A.mem v a);
  in
  List.iter check [I.max_int; I.min_int; -1l; 0l];

  let a = A.init 7778 I.of_int in
  assert (A.mem 0l a);
  assert (A.mem 7777l a);
  assert (not (A.mem (-1l) a));
  assert (not (A.mem 7778l a));
  let check v =
    A.set a 1001 v;
    assert (A.mem v a);
  in
  List.iter check [I.max_int; I.min_int; -1l; 0l];

  (* [sort] [fast_sort] [stable_sort] *)
  let check_sort sort cmp a =
    let rec check_sorted a i =
      if i + 1 < A.length a then begin
        assert (cmp (A.get a i) (A.get a (i + 1)) <= 0);
        check_sorted a (i + 1);
      end
    in
    let rec check_permutation a b i =
      let p = Array.make (A.length a) true in
      let rec find lo hi x =
        assert (lo < hi);
        if hi = lo + 1 then begin
          assert (cmp (A.get a lo) x = 0);
          assert (p.(lo));
          p.(lo) <- false;
        end else begin
          let mid = (lo + hi) / 2 in
          assert (lo < mid && mid < hi);
          match cmp (A.get a (mid - 1)) x with
          | 0 when p.(mid - 1) -> find lo mid x
          | 0 -> find mid hi x
          | c when c < 0 -> find mid hi x
          | c when c > 0 -> find lo mid x
          | _ -> assert false
        end
      in
      A.iter (find 0 (A.length a)) b
    in
    let b = A.copy a in
    sort cmp a;
    check_sorted a 0;
    check_permutation a b 0;
  in
  Random.init 123;
  let rand_val _ =
    match Random.int 1000 with
    | n when n < 500 -> Random.int32 I.max_int
    | _ -> I.neg (Random.int32 I.max_int)
  in
  let check s =
    let a = A.init 5 I.of_int in
    check_sort s Stdlib.compare a; (* already sorted *)
    check_sort s (fun x y -> Stdlib.compare y x) a; (* reverse-sorted *)

    let a = A.init 6 I.of_int in
    check_sort s Stdlib.compare a; (* already sorted *)
    check_sort s (fun x y -> Stdlib.compare y x) a; (* reverse-sorted *)

    let a = A.of_list [I.max_int; I.min_int; -1l; 0l] in
    check_sort s Stdlib.compare a; (* already sorted *)
    check_sort s (fun x y -> Stdlib.compare y x) a; (* reverse-sorted *)

    let a = A.init 50000 rand_val in
    check_sort s Stdlib.compare a;
    let a = A.init 50001 rand_val in
    check_sort s Stdlib.compare a;
    let a = A.make 1000 1l in
    check_sort s Stdlib.compare a;
    let a = A.make 1001 1l in
    check_sort s Stdlib.compare a;
    let a = A.append (A.make 1000 1l) (A.make 1000 2l) in
    check_sort s Stdlib.compare a;
    let a = A.append (A.make 1001 1l) (A.make 1001 2l) in
    check_sort s Stdlib.compare a;
  in
  check A.sort;
  check A.stable_sort;
  check A.fast_sort;

  (* [to_seq] *)
  let check_seq a =
    let r = ref 0 in
    let f x =
      assert (A.get a !r = x);
      r := !r + 1;
    in
    let s = A.to_seq a in
    Seq.iter f s;
  in
  check_seq (A.init 999 I.of_int);
  check_seq (A.init 1000 I.of_int);
  check_seq (A.make 0 0l);

  (* [to_seqi] *)
  let check_seqi a =
    let r = ref 0 in
    let f (i, x) =
      assert (i = !r);
      assert (A.get a !r = x);
      r := !r + 1;
    in
    let s = A.to_seqi a in
    Seq.iter f s;
  in
  check_seqi (A.init 999 I.of_int);
  check_seqi (A.init 1000 I.of_int);
  check_seqi (A.make 0 0l);

  (* [of_seq] *)
  let r = ref 0 in
  let rec f () =
    if !r = 100 then Seq.Nil else begin
      let res = Seq.Cons (I.of_int !r, f) in
      r := !r + 1;
      res
    end
  in
  let a = A.of_seq f in
  assert (A.equal a (A.init 100 I.of_int));
  assert (A.equal (A.of_seq Seq.empty) (A.make 0 0l));

  (* [map_to_array] *)
  let r = ref 0 in
  let f x =
    assert (x = I.of_int !r);
    r := !r + 1;
    I.mul x 2l
  in
  let a = A.init 876 I.of_int in
  let ar1 = A.map_to_array f a in
  let ar2 = Array.init 876 (fun x -> I.of_int (2 * x)) in
  assert (ar1 = ar2);
  let ar = A.map_to_array (fun _ -> assert false) (A.make 0 0l) in
  assert (ar = [| |]);

  (* [map_from_array] *)
  let r = ref 0 in
  let f x =
    assert (x = I.of_int !r);
    r := !r + 1;
    I.mul x 2l
  in
  let ar = Array.init 876 I.of_int in
  let a1 = A.map_from_array f ar in
  let a2 = A.init 876 (fun x -> I.of_int (2 * x)) in
  assert (A.equal a1 a2);
  let a = A.map_from_array (fun _ -> assert false) [| |] in
  assert (A.equal a (A.make 0 0l));

  (* comparisons *)
  (* No polymorphic compare yet *)
  (* let normalize_comparison n =
    if n = 0 then 0 else if n < 0 then -1 else 1
  in
  let check c l1 l2 =
    assert (c = (normalize_comparison (compare (A.of_list l1) (A.of_list l2))))
  in
  check 0    [0l; 1l; -4l; I.max_int; I.min_int]
             [0l; 1l; -4l; I.max_int; I.min_int];
  check (-1) [0l; 1l; -4l; I.max_int; I.min_int]
             [0l; 1l; -4l; I.max_int; I.(add min_int 1l)];
  check (-1) [0l; 1l; -4l; I.max_int; 45096843l]
             [0l; 1l; -4l; I.max_int; 45096844l];
  check 1    [0l; 2l; -4l]
             [0l; 0l; 3l];
  check 1    [0l; 2l; -4l]
             [I.min_int; 0l; 3l]; *)

  (* [unsafe_get] [unsafe_set] *)
  let a = A.make 3 0l in
  for i = 0 to 2 do A.unsafe_set a i (I.of_int i) done;
  for i = 0 to 2 do assert (A.unsafe_get a i = I.of_int i) done;

  let a = A.make 4 0l in
  for i = 0 to 3 do A.unsafe_set a i (I.of_int i) done;
  for i = 0 to 3 do assert (A.unsafe_get a i = I.of_int i) done;

  (* I/O *)
  (* No marshalling yet *)
  (* let test_structured_io value =
    let (tmp, oc) =
      Filename.open_temp_file ~mode:[Open_binary] "int64_array" ".data"
    in
    Marshal.to_channel oc value [];
    close_out oc;
    let ic = open_in_bin tmp in
    let value' = Marshal.from_channel ic in
    close_in ic;
    Sys.remove tmp;
    assert (compare value value' = 0)
  in
  let l = [0l; 1l; -4l; I.max_int; I.min_int; 31415926l] in
  test_structured_io (A.of_list l); *)

end

module T = Test (Int32_array)
module T2 = Test (Int32_u_array)

(* Extra tests for functions not covered above *)
module Int32_u = Stdlib__Int32_u
let () =
  let open Std_Int32_u_array in
  let module I = Int32 in
  let to_boxed = Int32_u.to_int32 in
  let u_of_int = Int32_u.of_int in
  let (+.) x y = I.add x y in
  let rec check_i_upto a i =
    if i >= 0 then begin
      assert (to_boxed (get a i) = I.of_int i);
      check_i_upto a (i - 1);
    end
  in

  let check_i a = check_i_upto a (length a - 1) in
  let check_inval f arg =
    match f arg with
    | _ -> assert false
    | exception (Invalid_argument _) -> ()
    | exception _ -> assert false
  in

  (* make_matrix *)
  check_inval (make_matrix (-1) 1) (u_of_int 1);
  check_inval (make_matrix 1 (-1)) (u_of_int 1);
  let check_matrix a =
    let row_len = Array.length a in
    assert (row_len > 0);
    let col_len = length (a.(0)) in
    for row = 0 to (row_len - 1) do
      assert (length (a.(row)) = col_len);
      for col = 0 to (col_len - 1) do
        assert Int32_u.(equal (get (a.(row)) col) (of_int 1))
      done
    done in
  let a = make_matrix 100 100 (u_of_int 1) in
  check_matrix a;
  let a = make_matrix 101 100 (u_of_int 1) in
  check_matrix a;
  let a = make_matrix 101 101 (u_of_int 1) in
  check_matrix a;
  let a = make_matrix 100 101 (u_of_int 1) in
  check_matrix a;

  (* for_all2 *)
  let test a =
    let r = ref 0l in
    let f x y =
      let x = to_boxed x in
      let y = to_boxed y in
      assert (x = !r);
      assert (y = !r);
      r := x +. 1l;
      true
    in
    assert (for_all2 f a a);
    let f x y =
      let x = to_boxed x in
      let y = to_boxed y in
      assert (x = 0l); assert (y = 0l); false in
    if length a > 0 then assert (not (for_all2 f a a))

  in
  let a = init 777 u_of_int in
  test a;
  let a = init 778 u_of_int in
  test a;
  let a = init 0 u_of_int in
  test a;
  check_inval (fun x -> for_all2 (fun _ _ -> true) (make 100 x) (make 101 x))
    (u_of_int 1);

  (* exists2 *)
  let test a =
    let r = ref 0l in
    let f x y =
      let x = to_boxed x in
      let y = to_boxed y in
      assert (x = !r);
      assert (y = !r);
      r := x +. 1l;
      false
    in
    assert (not (exists2 f a a));
    let f x y =
      let x = to_boxed x in
      let y = to_boxed y in
      assert (x = 0l); assert (y = 0l); true in
    if length a > 0 then assert (exists2 f a a)

  in
  let a = init 777 u_of_int in
  test a;
  let a = init 778 u_of_int in
  test a;
  let a = init 0 u_of_int in
  test a;
  check_inval (fun x -> exists2 (fun _ _ -> true) (make 100 x) (make 101 x))
    (u_of_int 1);

  (* static blocks *)
  let r = [| #0l; #1l; #2l; #3l; #4l; #5l;
             #6l; #7l; #8l; #9l; #10l; #11l;
             #12l; #13l; #14l; #15l; #16l; #17l;
             #18l; #19l; #20l; #21l; #22l; #23l;
             #24l; #25l; #26l; #27l; #28l; #29l;
             #30l; #31l; #32l; #33l; #34l; #35l;
             #36l; #37l; #38l; #39l; #40l; #41l;
             #42l; #43l; #44l; #45l; #46l; #47l;
             #48l; #49l; #50l; #51l; #52l; #53l;
             #54l; #55l; #56l; #57l; #58l; #59l;
             #60l; #61l; #62l; #63l; #64l; #65l;
             #66l; #67l; #68l; #69l; #70l; #71l;
             #72l; #73l; #74l; #75l; #76l; #77l;
             #78l; #79l; #80l; #81l; #82l; #83l;
             #84l; #85l; #86l; #87l; #88l; #89l;
             #90l; #91l; #92l; #93l; #94l; #95l;
             #96l; #97l; #98l; #99l; #100l; #101l;
             #102l; #103l; #104l; #105l; #106l; #107l;
             #108l; #109l; #110l; #111l; #112l; #113l;
             #114l; #115l; #116l; #117l; #118l; #119l;
             #120l; #121l; #122l; #123l; #124l; #125l;
             #126l; #127l; #128l; #129l; #130l; #131l;
             #132l; #133l; #134l; #135l; #136l; #137l;
             #138l; #139l; #140l; #141l; #142l; #143l;
             #144l; #145l; #146l; #147l; #148l; #149l;
             #150l; #151l; #152l; #153l; #154l; #155l;
             #156l; #157l; #158l; #159l; #160l; #161l;
             #162l; #163l; #164l; #165l; #166l; #167l;
             #168l; #169l; #170l; #171l; #172l; #173l;
             #174l; #175l; #176l; #177l; #178l; #179l;
             #180l; #181l; #182l; #183l; #184l; #185l;
             #186l; #187l; #188l; #189l; #190l; #191l;
             #192l; #193l; #194l; #195l; #196l; #197l;
             #198l; #199l |]
  in
  check_i r;
  let r = [| #0l; #1l; #2l; #3l; #4l; #5l;
             #6l; #7l; #8l; #9l; #10l; #11l;
             #12l; #13l; #14l; #15l; #16l; #17l;
             #18l; #19l; #20l; #21l; #22l; #23l;
             #24l; #25l; #26l; #27l; #28l; #29l;
             #30l; #31l; #32l; #33l; #34l; #35l;
             #36l; #37l; #38l; #39l; #40l; #41l;
             #42l; #43l; #44l; #45l; #46l; #47l;
             #48l; #49l; #50l; #51l; #52l; #53l;
             #54l; #55l; #56l; #57l; #58l; #59l;
             #60l; #61l; #62l; #63l; #64l; #65l;
             #66l; #67l; #68l; #69l; #70l; #71l;
             #72l; #73l; #74l; #75l; #76l; #77l;
             #78l; #79l; #80l; #81l; #82l; #83l;
             #84l; #85l; #86l; #87l; #88l; #89l;
             #90l; #91l; #92l; #93l; #94l; #95l;
             #96l; #97l; #98l; #99l; #100l; #101l;
             #102l; #103l; #104l; #105l; #106l; #107l;
             #108l; #109l; #110l; #111l; #112l; #113l;
             #114l; #115l; #116l; #117l; #118l; #119l;
             #120l; #121l; #122l; #123l; #124l; #125l;
             #126l; #127l; #128l; #129l; #130l; #131l;
             #132l; #133l; #134l; #135l; #136l; #137l;
             #138l; #139l; #140l; #141l; #142l; #143l;
             #144l; #145l; #146l; #147l; #148l; #149l;
             #150l; #151l; #152l; #153l; #154l; #155l;
             #156l; #157l; #158l; #159l; #160l; #161l;
             #162l; #163l; #164l; #165l; #166l; #167l;
             #168l; #169l; #170l; #171l; #172l; #173l;
             #174l; #175l; #176l; #177l; #178l; #179l;
             #180l; #181l; #182l; #183l; #184l; #185l;
             #186l; #187l; #188l; #189l; #190l; #191l;
             #192l; #193l; #194l; #195l; #196l; #197l;
             #198l; #199l; #200l |]
  in
  check_i r;
  (* dynamic blocks *)
  let[@inline never] f x = x in
  let r = [| f #0l; f #1l; f #2l; f #3l; f #4l; f #5l;
             f #6l; f #7l; f #8l; f #9l; f #10l; f #11l;
             f #12l; f #13l; f #14l; f #15l; f #16l; f #17l;
             f #18l; f #19l; f #20l; f #21l; f #22l; f #23l;
             f #24l; f #25l; f #26l; f #27l; f #28l; f #29l;
             f #30l; f #31l; f #32l; f #33l; f #34l; f #35l;
             f #36l; f #37l; f #38l; f #39l; f #40l; f #41l;
             f #42l; f #43l; f #44l; f #45l; f #46l; f #47l;
             f #48l; f #49l; f #50l; f #51l; f #52l; f #53l;
             f #54l; f #55l; f #56l; f #57l; f #58l; f #59l;
             f #60l; f #61l; f #62l; f #63l; f #64l; f #65l;
             f #66l; f #67l; f #68l; f #69l; f #70l; f #71l;
             f #72l; f #73l; f #74l; f #75l; f #76l; f #77l;
             f #78l; f #79l; f #80l; f #81l; f #82l; f #83l;
             f #84l; f #85l; f #86l; f #87l; f #88l; f #89l;
             f #90l; f #91l; f #92l; f #93l; f #94l; f #95l;
             f #96l; f #97l; f #98l; f #99l; f #100l; f #101l;
             f #102l; f #103l; f #104l; f #105l; f #106l; f #107l;
             f #108l; f #109l; f #110l; f #111l; f #112l; f #113l;
             f #114l; f #115l; f #116l; f #117l; f #118l; f #119l;
             f #120l; f #121l; f #122l; f #123l; f #124l; f #125l;
             f #126l; f #127l; f #128l; f #129l; f #130l; f #131l;
             f #132l; f #133l; f #134l; f #135l; f #136l; f #137l;
             f #138l; f #139l; f #140l; f #141l; f #142l; f #143l;
             f #144l; f #145l; f #146l; f #147l; f #148l; f #149l;
             f #150l; f #151l; f #152l; f #153l; f #154l; f #155l;
             f #156l; f #157l; f #158l; f #159l; f #160l; f #161l;
             f #162l; f #163l; f #164l; f #165l; f #166l; f #167l;
             f #168l; f #169l; f #170l; f #171l; f #172l; f #173l;
             f #174l; f #175l; f #176l; f #177l; f #178l; f #179l;
             f #180l; f #181l; f #182l; f #183l; f #184l; f #185l;
             f #186l; f #187l; f #188l; f #189l; f #190l; f #191l;
             f #192l; f #193l; f #194l; f #195l; f #196l; f #197l;
             f #198l; f #199l |]
  in
  check_i r;
  let r = [| f #0l; f #1l; f #2l; f #3l; f #4l; f #5l;
             f #6l; f #7l; f #8l; f #9l; f #10l; f #11l;
             f #12l; f #13l; f #14l; f #15l; f #16l; f #17l;
             f #18l; f #19l; f #20l; f #21l; f #22l; f #23l;
             f #24l; f #25l; f #26l; f #27l; f #28l; f #29l;
             f #30l; f #31l; f #32l; f #33l; f #34l; f #35l;
             f #36l; f #37l; f #38l; f #39l; f #40l; f #41l;
             f #42l; f #43l; f #44l; f #45l; f #46l; f #47l;
             f #48l; f #49l; f #50l; f #51l; f #52l; f #53l;
             f #54l; f #55l; f #56l; f #57l; f #58l; f #59l;
             f #60l; f #61l; f #62l; f #63l; f #64l; f #65l;
             f #66l; f #67l; f #68l; f #69l; f #70l; f #71l;
             f #72l; f #73l; f #74l; f #75l; f #76l; f #77l;
             f #78l; f #79l; f #80l; f #81l; f #82l; f #83l;
             f #84l; f #85l; f #86l; f #87l; f #88l; f #89l;
             f #90l; f #91l; f #92l; f #93l; f #94l; f #95l;
             f #96l; f #97l; f #98l; f #99l; f #100l; f #101l;
             f #102l; f #103l; f #104l; f #105l; f #106l; f #107l;
             f #108l; f #109l; f #110l; f #111l; f #112l; f #113l;
             f #114l; f #115l; f #116l; f #117l; f #118l; f #119l;
             f #120l; f #121l; f #122l; f #123l; f #124l; f #125l;
             f #126l; f #127l; f #128l; f #129l; f #130l; f #131l;
             f #132l; f #133l; f #134l; f #135l; f #136l; f #137l;
             f #138l; f #139l; f #140l; f #141l; f #142l; f #143l;
             f #144l; f #145l; f #146l; f #147l; f #148l; f #149l;
             f #150l; f #151l; f #152l; f #153l; f #154l; f #155l;
             f #156l; f #157l; f #158l; f #159l; f #160l; f #161l;
             f #162l; f #163l; f #164l; f #165l; f #166l; f #167l;
             f #168l; f #169l; f #170l; f #171l; f #172l; f #173l;
             f #174l; f #175l; f #176l; f #177l; f #178l; f #179l;
             f #180l; f #181l; f #182l; f #183l; f #184l; f #185l;
             f #186l; f #187l; f #188l; f #189l; f #190l; f #191l;
             f #192l; f #193l; f #194l; f #195l; f #196l; f #197l;
             f #198l; f #199l; f #200l |]
  in
  check_i r;
  check_i [| #0l; ((fun x -> x) #1l)|];
  check_i [| #0l; ((fun x -> x) #1l); #2l|];

  let () =
    let (=) = Int32_u.equal in
    (* match statement *)
    let d = [| #1l; #2l |] in
    (match d with
      | [| a; b |] ->
        assert (a = #1l);
        assert (b = #2l)
      | _ -> assert false);

    (* let statement pattern *)
    let a = [||] in
    let b = [| #1l |] in
    let c = append a b in
    let[@warning "-8"] [| d |] = c in
    assert (d = #1l);

    (* function argument pattern *)
    let[@warning "-8"] f [| b |] = b in
    assert (f [| #1l |] = #1l)
  in
  ()
