(* TEST
 readonly_files = "int64_u_array.ml"
 modules = "${readonly_files}"

 * bytecode
   flags = "-extension layouts_alpha"
 * bytecode
   flags = "-extension layouts_beta"
 * native
   flags = "-extension layouts_alpha"
 * native
   flags = "-extension layouts_beta"
*)

(* Do not edit this file directly.
   Change "*.ml.template" files and run "gen.py" instead. *)

open Printf

module type S = sig
  type t
  val length : t -> int
  val get : t -> int -> int64
  val set : t -> int -> int64 -> unit
  val make : int -> int64 -> t
  val init : int -> (int -> int64) -> t
  val append : t -> t -> t
  val concat : t list -> t
  val sub : t -> int -> int -> t
  val copy : t -> t
  val fill : t -> int -> int -> int64 -> unit
  val blit : t -> int -> t -> int -> int -> unit
  val to_list : t -> int64 list
  val of_list : int64 list -> t
  val iter : (int64 -> unit) -> t -> unit
  val iteri : (int -> int64 -> unit) -> t -> unit
  val map : (int64 -> int64) -> t -> t
  val mapi : (int -> int64 -> int64) -> t -> t
  val fold_left : ('a -> int64 -> 'a) -> 'a -> t -> 'a
  val fold_right : (int64 -> 'a -> 'a) -> t -> 'a -> 'a
  val iter2 : (int64 -> int64 -> unit) -> t -> t -> unit
  val map2 : (int64 -> int64 -> int64) -> t -> t -> t
  val for_all : (int64 -> bool) -> t -> bool
  val exists : (int64 -> bool) -> t -> bool
  val mem : int64 -> t -> bool
  val sort : (int64 -> int64 -> int) -> t -> unit
  val stable_sort : (int64 -> int64 -> int) -> t -> unit
  val fast_sort : (int64 -> int64 -> int) -> t -> unit
  val to_seq : t -> int64 Seq.t
  val to_seqi : t -> (int * int64) Seq.t
  val of_seq : int64 Seq.t -> t
  val map_to_array : (int64 -> 'a) -> t -> 'a array
  val map_from_array : ('a -> int64) -> 'a array -> t
  val unsafe_get : t -> int -> int64
  val unsafe_set : t -> int -> int64 -> unit
  val equal : t -> t -> bool
  (* From Sys, rather than Float.Array *)
  val max_length : int
end

module Int64_array : S = struct
  include Stdlib.Array
  let map_to_array f a = map f a
  let map_from_array f a = map f a
  type t = int64 array
  let max_length = Sys.max_array_length
  let equal = for_all2 (fun x y -> x = y)
end

module Std_Int64_u_array = Int64_u_array
module Int64_u_array : S = struct
  include Int64_u_array

  module Int64_u = Stdlib__Int64_u

  let to_boxed = Int64_u.to_int64
  let of_boxed = Int64_u.of_int64

  type t = int64# array

  let empty () = make 0 (of_boxed 0L)
  let to_seq a =
    let rec aux i () =
      if i < length a
      then
        let x = unsafe_get a i in
        Seq.Cons (to_boxed x, aux (i+1))
      else Seq.Nil
    in
    aux 0

  let to_seqi a =
    let rec aux i () =
      if i < length a
      then
        let x = unsafe_get a i in
        Seq.Cons ((i,to_boxed x), aux (i+1))
      else Seq.Nil
    in
    aux 0

  let of_rev_list = function
      [] -> empty ()
    | hd::tl as l ->
      let len = List.length l in
      let a = make len (of_boxed hd) in
      let rec fill i = function
          [] -> a
        | hd::tl -> unsafe_set a i (of_boxed hd); fill (i-1) tl
      in
      fill (len-2) tl

  let of_seq i =
    let l = Seq.fold_left (fun acc x -> x::acc) [] i in
    of_rev_list l


  let to_list t = fold_right (fun f l -> (to_boxed f)::l) t []
  (* let res = ref [] in
   * iter (fun f -> res := (to_boxed f) :: !res);
   * List.rev res *)

  let of_list l =
    let len = List.length l in
    let res = create len #0L in
    List.iteri (fun idx f -> set res idx (of_boxed f)) l;
    res
  let max_length = Sys.max_array_length
  let get t idx = to_boxed (get t idx)
  let set t idx v = set t idx (of_boxed v)

  let make l f = make l (of_boxed f)
  let init l f = init l (fun i -> of_boxed (f i))
  let fill a ofs len v = fill a ofs len (of_boxed v)
  let iter f t = iter (fun v -> f (to_boxed v)) t
  let iteri f t = iteri (fun i v -> f i (to_boxed v)) t
  let map f t = map (fun v -> of_boxed (f (to_boxed v))) t
  let mapi f t = mapi (fun i v -> of_boxed (f i (to_boxed v))) t
  let fold_left f acc t = fold_left (fun acc v -> f acc (to_boxed v)) acc t
  let fold_right f t acc = fold_right (fun v acc -> f (to_boxed v) acc) t acc

  let iter2 f a b = iter2 (fun v1 v2 -> f (to_boxed v1) (to_boxed v2)) a b
  let map2 f a b = map2 (fun v1 v2 -> of_boxed (f (to_boxed v1) (to_boxed v2))) a b
  let for_all f t = for_all (fun v -> f (to_boxed v)) t
  let exists f t = exists (fun v -> f (to_boxed v)) t
  let mem v t = mem (of_boxed v) t
  let sort f t = sort (fun a b -> f (to_boxed a) (to_boxed b)) t
  let stable_sort f t = stable_sort (fun a b -> f (to_boxed a) (to_boxed b)) t
  let fast_sort f t = fast_sort (fun a b -> f (to_boxed a) (to_boxed b)) t

  let map_to_array f t =
    if length t = 0 then [||] else begin
      let res = Array.make (length t) (f (get t 0)) in
      iteri (fun idx v -> if idx > 0 then Array.set res idx (f v)) t;
      res
    end

  let map_from_array f a =
    if Array.length a = 0 then empty () else begin
      let res = make (Array.length a) (f (Array.get a 0)) in
      Array.iteri (fun idx v -> if idx > 0 then set res idx (f v)) a;
      res
    end

  let unsafe_get t idx = to_boxed (unsafe_get t idx)
  let unsafe_set t idx v = unsafe_set t idx (of_boxed v)
  let equal = for_all2 (fun x y -> to_boxed x = to_boxed y)
end


module Test (A : S) : sig end = struct

  (* auxiliary functions *)

  let module I = Int64 in
  let rec check_i_upto a i =
    if i >= 0 then begin
      assert (A.get a i = I.of_int i);
      check_i_upto a (i - 1);
    end
  in

  let check_i a = check_i_upto a (A.length a - 1) in

  let check_inval f arg =
    match f arg with
    | _ -> assert false
    | exception (Invalid_argument _) -> ()
    | exception _ -> assert false
  in

  (* [make] [set] [get] *)
  let a = A.make 1000 1L in
  for i = 0 to 499 do A.set a i (I.of_int i) done;
  let rec loop i =
    if i >= 0 then begin
      assert (A.get a i = (if i < 500 then I.of_int i else 1L));
      loop (i - 1);
    end
  in loop 999;
  check_inval (A.get a) (-1);
  check_inval (A.get a) (1000);
  check_inval (fun i -> A.set a i 1L) (-1);
  check_inval (fun i -> A.set a i 1L) 1000;
  check_inval (fun i -> A.make i 1L) (-1);
  check_inval (fun i -> A.make i 1L) (A.max_length + 1);

  let a = A.make 1001 1L in
  for i = 0 to 499 do A.set a i (I.of_int i) done;
  let rec loop i =
    if i >= 0 then begin
      assert (A.get a i = (if i < 500 then I.of_int i else 1L));
      loop (i - 1);
    end
  in loop 1000;
  check_inval (A.get a) (-1);
  check_inval (A.get a) (1001);
  check_inval (fun i -> A.set a i 1L) (-1);
  check_inval (fun i -> A.set a i 1L) 1001;

  (* [length] *)
  let test_length l = assert (l = (A.length (A.make l 1L))) in
  test_length 0;
  test_length 1;
  test_length 10;
  test_length 25;
  test_length 255;
  test_length 256;
  test_length 1000;
  test_length 1001;
  test_length 123456;

  (* [init] *)
  let a = A.init 1000 I.of_int in
  check_i a;
  let a = A.init 1001 I.of_int in
  check_i a;
  check_inval (fun i -> A.init i I.of_int) (-1);
  check_inval (fun i -> A.init i I.of_int) (A.max_length + 1);

  (* [append] *)
  let check m n =
    let a = A.init m I.of_int in
    let b = A.init n (fun x -> I.of_int (x + m)) in
    let c = A.append a b in
    assert (A.length c = (m + n));
    check_i c;
  in
  check 0 0;
  check 0 100;
  check 1 100;
  check 100 0;
  check 100 1;
  check 100 100;
  check 1000 1000;
  check 1000 1001;
  check 1001 1000;
  check 1001 1001;
  (* check_inval omitted *)

  (* [concat] *)
  let check l =
    let f (len, acc) n =
      (len + n, A.init n (fun i -> I.of_int (len + i)) :: acc)
    in
    let (total, ll) = List.fold_left f (0, []) l in
    let b = A.concat (List.rev ll) in
    assert (A.length b = total);
    check_i b;
  in
  check [0; 0; 0];
  check [1; 10; 100];
  check [10; 0];
  check [0];
  check [1000; 1000; 1000];
  check [];
  check [1001; 1000; 1000];
  check [1000; 1001; 1000];
  check [1000; 1000; 1001];
  check [1001; 1001; 1001];
  (* check_inval omitted *)

  (* [sub] *)
  let a = A.init 1000 (fun i -> I.of_int (i - 100)) in
  let b = A.sub a 100 200 in
  check_i b;
  assert (A.length b = 200);
  let b = A.sub a 1000 0 in
  check_i (A.sub a 1000 0);
  assert  (A.length b = 0);
  check_inval (A.sub a (-1)) 0;
  check_inval (A.sub a 0) (-1);
  check_inval (A.sub a 0) 1001;
  check_inval (A.sub a 1000) 1;

  let a = A.init 1001 (fun i -> I.of_int (i - 101)) in
  let b = A.sub a 101 199 in
  check_i b;
  assert (A.length b = 199);
  let b = A.sub a 1001 0 in
  check_i (A.sub a 1001 0);
  assert  (A.length b = 0);
  check_inval (A.sub a (-1)) 0;
  check_inval (A.sub a 0) (-1);
  check_inval (A.sub a 0) 1002;
  check_inval (A.sub a 1001) 1;

  (* [copy] *)
  let check len =
    let a = A.init len I.of_int in
    let b = A.copy a in
    check_i b;
    assert (A.length b = len);
  in
  check 0;
  check 1;
  check 128;
  check 1023;

  (* [blit] [fill] *)
  let test_blit_fill data initval ofs len =
    let a = A.of_list data in
    let b = A.make (List.length data) 1L in
    A.blit a 0 b 0 (A.length b);
    assert (A.equal a b);
    A.fill b ofs len initval;
    let rec check i = function
      | [] -> ()
      | hd :: tl ->
          assert (A.get b i = (if i >= ofs && i < ofs + len
                               then initval else hd));
          check (i + 1) tl;
    in
    check 0 data
  in
  test_blit_fill [1L;2L;5L;8L;-100L;2120000000L] 3L 3 2;
  let a = A.make 100 0L in
  check_inval (A.fill a (-1) 0) 1L;
  check_inval (A.fill a 0 (-1)) 1L;
  check_inval (A.fill a 0 101) 1L;
  check_inval (A.fill a 100 1) 1L;
  check_inval (A.fill a 101 0) 1L;
  check_inval (A.blit a (-1) a 0) 0;
  check_inval (A.blit a 0 a 0) (-1);
  check_inval (A.blit a 0 a 0) 101;
  check_inval (A.blit a 100 a 0) 1;
  check_inval (A.blit a 101 a 0) 0;
  check_inval (A.blit a 0 a (-1)) 0;
  check_inval (A.blit a 0 a 100) 1;
  check_inval (A.blit a 0 a 101) 0;
  let a = A.make 101 0L in
  check_inval (A.fill a (-1) 0) 1L;
  check_inval (A.fill a 0 (-1)) 1L;
  check_inval (A.fill a 0 102) 1L;
  check_inval (A.fill a 101 1) 1L;
  check_inval (A.fill a 102 0) 1L;
  check_inval (A.blit a (-1) a 0) 0;
  check_inval (A.blit a 0 a 0) (-1);
  check_inval (A.blit a 0 a 0) 102;
  check_inval (A.blit a 101 a 0) 1;
  check_inval (A.blit a 102 a 0) 0;
  check_inval (A.blit a 0 a (-1)) 0;
  check_inval (A.blit a 0 a 101) 1;
  check_inval (A.blit a 0 a 102) 0;
  let test_blit_overlap a ofs1 ofs2 len =
    let a = A.of_list a in
    let b = A.copy a in
    A.blit a ofs1 a ofs2 len;
    for i = 0 to len - 1 do
      assert (A.get b (ofs1 + i) = A.get a (ofs2 + i))
    done
  in
  test_blit_overlap [1L; 2L; 3L; 4L] 1 2 2;

  (* [to_list] [of_list] *)
  let a = A.init 1000 I.of_int in
  assert (A.equal a (A.of_list (A.to_list a)));
  let a = A.init 1001 I.of_int in
  assert (A.equal a (A.of_list (A.to_list a)));
  let a = A.init 0 I.of_int in
  assert (A.equal a (A.of_list (A.to_list a)));
  (* check_inval omitted *)

  (* [iter] *)
  let a = A.init 300 (I.of_int) in
  let r = ref 0L in
  A.iter (fun x -> assert (x = !r); r := I.add x 1L) a;
  A.iter (fun _ -> assert false) (A.make 0 0L);
  assert (!r = 300L);

  let a = A.init 301 (I.of_int) in
  let r = ref 0L in
  A.iter (fun x -> assert (x = !r); r := I.add x 1L) a;
  assert (!r = 301L);

  (* [iteri] *)
  let a = A.init 300 I.of_int in
  let r = ref 0 in
  let f i x =
    assert (i = !r);
    assert (x = I.of_int i);
    r := i + 1
  in
  A.iteri f a;
  A.iteri (fun _ _ -> assert false) (A.make 0 0L);
  assert (!r = 300);

  let a = A.init 301 I.of_int in
  let r = ref 0 in
  let f i x =
    assert (i = !r);
    assert (x = I.of_int i);
    r := i + 1
  in
  A.iteri f a;
  A.iteri (fun _ _ -> assert false) (A.make 0 0L);
  assert (!r = 301);

  (* [map], test result and order of evaluation *)
  let a = A.init 500 I.of_int in
  let r = ref 0L in
  let f x =
    assert (x = !r);
    r := I.add !r 1L;
    I.sub x 1L
  in
  let b = A.map f a in
  check_i (A.sub b 1 499);

  let a = A.init 501 I.of_int in
  let r = ref 0L in
  let f x =
    assert (x = !r);
    r := I.add !r 1L;
    I.sub x 1L
  in
  let b = A.map f a in
  check_i (A.sub b 1 500);

  (* [mapi], test result and order of evaluation *)
  let a = A.init 500 I.of_int in
  let r = ref 0L in
  let f i x =
    assert (x = I.of_int i);
    assert (x = !r);
    r := I.add !r 1L;
    I.sub x 1L
  in
  let b = A.mapi f a in
  check_i (A.sub b 1 499);

  let a = A.init 501 I.of_int in
  let r = ref 0L in
  let f i x =
    assert (x = I.of_int i);
    assert (x = !r);
    r := I.add !r 1L;
    I.sub x 1L
  in
  let b = A.mapi f a in
  check_i (A.sub b 1 500);

  (* [fold_left], test result and order of evaluation *)
  let a = A.init 500 I.of_int in
  let f acc x =
    assert (acc = x);
    I.add x 1L
  in
  let acc = A.fold_left f 0L a in
  assert (acc = 500L);

  let a = A.init 501 I.of_int in
  let acc = A.fold_left f 0L a in
  assert (acc = 501L);

  (* [fold_right], test result and order of evaluation *)
  let a = A.init 500 I.of_int in
  let f x acc =
    assert (x = I.sub acc 1L);
    x
  in
  let acc = A.fold_right f a 500L in
  assert (acc = 0L);

  let a = A.init 501 I.of_int in
  let acc = A.fold_right f a 501L in
  assert (acc = 0L);

  (* [iter2], test result and order of evaluation *)
  let a = A.init 123 I.of_int in
  let b = A.init 123 I.of_int in
  let r = ref 0L in
  let f x y =
    assert (x = !r);
    assert (y = !r);
    r := I.add!r 1L;
  in
  A.iter2 f a b;
  let c = A.make 456 0L in
  check_inval (A.iter2 (fun _ _ -> assert false) a) c;
  check_inval (A.iter2 (fun _ _ -> assert false) c) a;

  let a = A.init 124 I.of_int in
  let b = A.init 124 I.of_int in
  let r = ref 0L in
  let f x y =
    assert (x = !r);
    assert (y = !r);
    r := I.add !r 1L;
  in
  A.iter2 f a b;

  (* [map2], test result and order of evaluation *)
  let a = A.init 456 I.of_int in
  let b = A.init 456 (fun i -> I.(mul (of_int i) 2L)) in
  let r = ref 0L in
  let f x y =
    assert (x = !r);
    assert (y = I.mul !r 2L);
    r := I.add !r 1L;
    I.(neg (sub x y))
  in
  let c = A.map2 f a b in
  check_i c;
  let d = A.make 455 0L in
  check_inval (A.map2 (fun _ _ -> assert false) a) d;
  check_inval (A.map2 (fun _ _ -> assert false) d) a;

  let a = A.init 457 I.of_int in
  let b = A.init 457 (fun i -> I.(mul (of_int i) 2L)) in
  let r = ref 0L in
  let f x y =
    assert (x = !r);
    assert (y = I.mul !r 2L);
    r := I.add !r 1L;
    I.(neg (sub x y))
  in
  let c = A.map2 f a b in
  check_i c;

  (* [for_all], test result and order of evaluation *)
  let a = A.init 777 I.of_int in
  let r = ref 0L in
  let f x =
    assert (x = !r);
    r := I.add x 1L;
    true
  in
  assert (A.for_all f a);
  let f x = assert (x = 0L); false in
  assert (not (A.for_all f a));

  let a = A.init 778 I.of_int in
  let r = ref 0L in
  let f x =
    assert (x = !r);
    r := I.add x 1L;
    true
  in
  assert (A.for_all f a);
  let f x = assert (x = 0L); false in
  assert (not (A.for_all f a));

  (* [exists], test result and order of evaluation *)
  let a = A.init 777 I.of_int in
  let r = ref 0L in
  let f x =
    assert (x = !r);
    r := I.add x 1L;
    false
  in
  assert (not (A.exists f a));
  let f x = assert (x = 0L); true in
  assert (A.exists f a);

  let a = A.init 778 I.of_int in
  let r = ref 0L in
  let f x =
    assert (x = !r);
    r := I.add x 1L;
    false
  in
  assert (not (A.exists f a));
  let f x = assert (x = 0L); true in
  assert (A.exists f a);

  (* [mem] *)
  let a = A.init 7777 I.of_int in
  assert (A.mem 0L a);
  assert (A.mem 7776L a);
  assert (not (A.mem (-1L) a));
  assert (not (A.mem 7777L a));
  let check v =
    A.set a 1000 v;
    assert (A.mem v a);
  in
  List.iter check [I.max_int; I.min_int; -1L; 0L];

  let a = A.init 7778 I.of_int in
  assert (A.mem 0L a);
  assert (A.mem 7777L a);
  assert (not (A.mem (-1L) a));
  assert (not (A.mem 7778L a));
  let check v =
    A.set a 1001 v;
    assert (A.mem v a);
  in
  List.iter check [I.max_int; I.min_int; -1L; 0L];

  (* [sort] [fast_sort] [stable_sort] *)
  let check_sort sort cmp a =
    let rec check_sorted a i =
      if i + 1 < A.length a then begin
        assert (cmp (A.get a i) (A.get a (i + 1)) <= 0);
        check_sorted a (i + 1);
      end
    in
    let rec check_permutation a b i =
      let p = Array.make (A.length a) true in
      let rec find lo hi x =
        assert (lo < hi);
        if hi = lo + 1 then begin
          assert (cmp (A.get a lo) x = 0);
          assert (p.(lo));
          p.(lo) <- false;
        end else begin
          let mid = (lo + hi) / 2 in
          assert (lo < mid && mid < hi);
          match cmp (A.get a (mid - 1)) x with
          | 0 when p.(mid - 1) -> find lo mid x
          | 0 -> find mid hi x
          | c when c < 0 -> find mid hi x
          | c when c > 0 -> find lo mid x
          | _ -> assert false
        end
      in
      A.iter (find 0 (A.length a)) b
    in
    let b = A.copy a in
    sort cmp a;
    check_sorted a 0;
    check_permutation a b 0;
  in
  Random.init 123;
  let rand_val _ =
    match Random.int 1000 with
    | n when n < 500 -> Random.int64 I.max_int
    | _ -> I.neg (Random.int64 I.max_int)
  in
  let check s =
    let a = A.init 5 I.of_int in
    check_sort s Stdlib.compare a; (* already sorted *)
    check_sort s (fun x y -> Stdlib.compare y x) a; (* reverse-sorted *)

    let a = A.init 6 I.of_int in
    check_sort s Stdlib.compare a; (* already sorted *)
    check_sort s (fun x y -> Stdlib.compare y x) a; (* reverse-sorted *)

    let a = A.of_list [I.max_int; I.min_int; -1L; 0L] in
    check_sort s Stdlib.compare a; (* already sorted *)
    check_sort s (fun x y -> Stdlib.compare y x) a; (* reverse-sorted *)

    let a = A.init 50000 rand_val in
    check_sort s Stdlib.compare a;
    let a = A.init 50001 rand_val in
    check_sort s Stdlib.compare a;
    let a = A.make 1000 1L in
    check_sort s Stdlib.compare a;
    let a = A.make 1001 1L in
    check_sort s Stdlib.compare a;
    let a = A.append (A.make 1000 1L) (A.make 1000 2L) in
    check_sort s Stdlib.compare a;
    let a = A.append (A.make 1001 1L) (A.make 1001 2L) in
    check_sort s Stdlib.compare a;
  in
  check A.sort;
  check A.stable_sort;
  check A.fast_sort;

  (* [to_seq] *)
  let check_seq a =
    let r = ref 0 in
    let f x =
      assert (A.get a !r = x);
      r := !r + 1;
    in
    let s = A.to_seq a in
    Seq.iter f s;
  in
  check_seq (A.init 999 I.of_int);
  check_seq (A.init 1000 I.of_int);
  check_seq (A.make 0 0L);

  (* [to_seqi] *)
  let check_seqi a =
    let r = ref 0 in
    let f (i, x) =
      assert (i = !r);
      assert (A.get a !r = x);
      r := !r + 1;
    in
    let s = A.to_seqi a in
    Seq.iter f s;
  in
  check_seqi (A.init 999 I.of_int);
  check_seqi (A.init 1000 I.of_int);
  check_seqi (A.make 0 0L);

  (* [of_seq] *)
  let r = ref 0 in
  let rec f () =
    if !r = 100 then Seq.Nil else begin
      let res = Seq.Cons (I.of_int !r, f) in
      r := !r + 1;
      res
    end
  in
  let a = A.of_seq f in
  assert (A.equal a (A.init 100 I.of_int));
  assert (A.equal (A.of_seq Seq.empty) (A.make 0 0L));

  (* [map_to_array] *)
  let r = ref 0 in
  let f x =
    assert (x = I.of_int !r);
    r := !r + 1;
    I.mul x 2L
  in
  let a = A.init 876 I.of_int in
  let ar1 = A.map_to_array f a in
  let ar2 = Array.init 876 (fun x -> I.of_int (2 * x)) in
  assert (ar1 = ar2);
  let ar = A.map_to_array (fun _ -> assert false) (A.make 0 0L) in
  assert (ar = [| |]);

  (* [map_from_array] *)
  let r = ref 0 in
  let f x =
    assert (x = I.of_int !r);
    r := !r + 1;
    I.mul x 2L
  in
  let ar = Array.init 876 I.of_int in
  let a1 = A.map_from_array f ar in
  let a2 = A.init 876 (fun x -> I.of_int (2 * x)) in
  assert (A.equal a1 a2);
  let a = A.map_from_array (fun _ -> assert false) [| |] in
  assert (A.equal a (A.make 0 0L));

  (* comparisons *)
  (* No polymorphic compare yet *)
  (* let normalize_comparison n =
    if n = 0 then 0 else if n < 0 then -1 else 1
  in
  let check c l1 l2 =
    assert (c = (normalize_comparison (compare (A.of_list l1) (A.of_list l2))))
  in
  check 0    [0L; 1L; -4L; I.max_int; I.min_int]
             [0L; 1L; -4L; I.max_int; I.min_int];
  check (-1) [0L; 1L; -4L; I.max_int; I.min_int]
             [0L; 1L; -4L; I.max_int; I.(add min_int 1L)];
  check (-1) [0L; 1L; -4L; I.max_int; 45096843L]
             [0L; 1L; -4L; I.max_int; 45096844L];
  check 1    [0L; 2L; -4L]
             [0L; 0L; 3L];
  check 1    [0L; 2L; -4L]
             [I.min_int; 0L; 3L]; *)

  (* [unsafe_get] [unsafe_set] *)
  let a = A.make 3 0L in
  for i = 0 to 2 do A.unsafe_set a i (I.of_int i) done;
  for i = 0 to 2 do assert (A.unsafe_get a i = I.of_int i) done;

  let a = A.make 4 0L in
  for i = 0 to 3 do A.unsafe_set a i (I.of_int i) done;
  for i = 0 to 3 do assert (A.unsafe_get a i = I.of_int i) done;

  (* I/O *)
  (* No marshalling yet *)
  (* let test_structured_io value =
    let (tmp, oc) =
      Filename.open_temp_file ~mode:[Open_binary] "int64_array" ".data"
    in
    Marshal.to_channel oc value [];
    close_out oc;
    let ic = open_in_bin tmp in
    let value' = Marshal.from_channel ic in
    close_in ic;
    Sys.remove tmp;
    assert (compare value value' = 0)
  in
  let l = [0L; 1L; -4L; I.max_int; I.min_int; 31415926L] in
  test_structured_io (A.of_list l); *)

end

module T = Test (Int64_array)
module T2 = Test (Int64_u_array)

(* Extra tests for functions not covered above *)
module Int64_u = Stdlib__Int64_u
let () =
  let open Std_Int64_u_array in
  let module I = Int64 in
  let to_boxed = Int64_u.to_int64 in
  let u_of_int = Int64_u.of_int in
  let (+.) x y = I.add x y in
  let rec check_i_upto a i =
    if i >= 0 then begin
      assert (to_boxed (get a i) = I.of_int i);
      check_i_upto a (i - 1);
    end
  in

  let check_i a = check_i_upto a (length a - 1) in
  let check_inval f arg =
    match f arg with
    | _ -> assert false
    | exception (Invalid_argument _) -> ()
    | exception _ -> assert false
  in

  (* make_matrix *)
  check_inval (make_matrix (-1) 1) (u_of_int 1);
  check_inval (make_matrix 1 (-1)) (u_of_int 1);
  let check_matrix a =
    let row_len = Array.length a in
    assert (row_len > 0);
    let col_len = length (a.(0)) in
    for row = 0 to (row_len - 1) do
      assert (length (a.(row)) = col_len);
      for col = 0 to (col_len - 1) do
        assert Int64_u.(equal (get (a.(row)) col) (of_int 1))
      done
    done in
  let a = make_matrix 100 100 (u_of_int 1) in
  check_matrix a;
  let a = make_matrix 101 100 (u_of_int 1) in
  check_matrix a;
  let a = make_matrix 101 101 (u_of_int 1) in
  check_matrix a;
  let a = make_matrix 100 101 (u_of_int 1) in
  check_matrix a;

  (* for_all2 *)
  let test a =
    let r = ref 0L in
    let f x y =
      let x = to_boxed x in
      let y = to_boxed y in
      assert (x = !r);
      assert (y = !r);
      r := x +. 1L;
      true
    in
    assert (for_all2 f a a);
    let f x y =
      let x = to_boxed x in
      let y = to_boxed y in
      assert (x = 0L); assert (y = 0L); false in
    if length a > 0 then assert (not (for_all2 f a a))

  in
  let a = init 777 u_of_int in
  test a;
  let a = init 778 u_of_int in
  test a;
  let a = init 0 u_of_int in
  test a;
  check_inval (fun x -> for_all2 (fun _ _ -> true) (make 100 x) (make 101 x))
    (u_of_int 1);

  (* exists2 *)
  let test a =
    let r = ref 0L in
    let f x y =
      let x = to_boxed x in
      let y = to_boxed y in
      assert (x = !r);
      assert (y = !r);
      r := x +. 1L;
      false
    in
    assert (not (exists2 f a a));
    let f x y =
      let x = to_boxed x in
      let y = to_boxed y in
      assert (x = 0L); assert (y = 0L); true in
    if length a > 0 then assert (exists2 f a a)

  in
  let a = init 777 u_of_int in
  test a;
  let a = init 778 u_of_int in
  test a;
  let a = init 0 u_of_int in
  test a;
  check_inval (fun x -> exists2 (fun _ _ -> true) (make 100 x) (make 101 x))
    (u_of_int 1);

  (* static blocks *)
  let r = [| #0L; #1L; #2L; #3L; #4L; #5L;
             #6L; #7L; #8L; #9L; #10L; #11L;
             #12L; #13L; #14L; #15L; #16L; #17L;
             #18L; #19L; #20L; #21L; #22L; #23L;
             #24L; #25L; #26L; #27L; #28L; #29L;
             #30L; #31L; #32L; #33L; #34L; #35L;
             #36L; #37L; #38L; #39L; #40L; #41L;
             #42L; #43L; #44L; #45L; #46L; #47L;
             #48L; #49L; #50L; #51L; #52L; #53L;
             #54L; #55L; #56L; #57L; #58L; #59L;
             #60L; #61L; #62L; #63L; #64L; #65L;
             #66L; #67L; #68L; #69L; #70L; #71L;
             #72L; #73L; #74L; #75L; #76L; #77L;
             #78L; #79L; #80L; #81L; #82L; #83L;
             #84L; #85L; #86L; #87L; #88L; #89L;
             #90L; #91L; #92L; #93L; #94L; #95L;
             #96L; #97L; #98L; #99L; #100L; #101L;
             #102L; #103L; #104L; #105L; #106L; #107L;
             #108L; #109L; #110L; #111L; #112L; #113L;
             #114L; #115L; #116L; #117L; #118L; #119L;
             #120L; #121L; #122L; #123L; #124L; #125L;
             #126L; #127L; #128L; #129L; #130L; #131L;
             #132L; #133L; #134L; #135L; #136L; #137L;
             #138L; #139L; #140L; #141L; #142L; #143L;
             #144L; #145L; #146L; #147L; #148L; #149L;
             #150L; #151L; #152L; #153L; #154L; #155L;
             #156L; #157L; #158L; #159L; #160L; #161L;
             #162L; #163L; #164L; #165L; #166L; #167L;
             #168L; #169L; #170L; #171L; #172L; #173L;
             #174L; #175L; #176L; #177L; #178L; #179L;
             #180L; #181L; #182L; #183L; #184L; #185L;
             #186L; #187L; #188L; #189L; #190L; #191L;
             #192L; #193L; #194L; #195L; #196L; #197L;
             #198L; #199L |]
  in
  check_i r;
  let r = [| #0L; #1L; #2L; #3L; #4L; #5L;
             #6L; #7L; #8L; #9L; #10L; #11L;
             #12L; #13L; #14L; #15L; #16L; #17L;
             #18L; #19L; #20L; #21L; #22L; #23L;
             #24L; #25L; #26L; #27L; #28L; #29L;
             #30L; #31L; #32L; #33L; #34L; #35L;
             #36L; #37L; #38L; #39L; #40L; #41L;
             #42L; #43L; #44L; #45L; #46L; #47L;
             #48L; #49L; #50L; #51L; #52L; #53L;
             #54L; #55L; #56L; #57L; #58L; #59L;
             #60L; #61L; #62L; #63L; #64L; #65L;
             #66L; #67L; #68L; #69L; #70L; #71L;
             #72L; #73L; #74L; #75L; #76L; #77L;
             #78L; #79L; #80L; #81L; #82L; #83L;
             #84L; #85L; #86L; #87L; #88L; #89L;
             #90L; #91L; #92L; #93L; #94L; #95L;
             #96L; #97L; #98L; #99L; #100L; #101L;
             #102L; #103L; #104L; #105L; #106L; #107L;
             #108L; #109L; #110L; #111L; #112L; #113L;
             #114L; #115L; #116L; #117L; #118L; #119L;
             #120L; #121L; #122L; #123L; #124L; #125L;
             #126L; #127L; #128L; #129L; #130L; #131L;
             #132L; #133L; #134L; #135L; #136L; #137L;
             #138L; #139L; #140L; #141L; #142L; #143L;
             #144L; #145L; #146L; #147L; #148L; #149L;
             #150L; #151L; #152L; #153L; #154L; #155L;
             #156L; #157L; #158L; #159L; #160L; #161L;
             #162L; #163L; #164L; #165L; #166L; #167L;
             #168L; #169L; #170L; #171L; #172L; #173L;
             #174L; #175L; #176L; #177L; #178L; #179L;
             #180L; #181L; #182L; #183L; #184L; #185L;
             #186L; #187L; #188L; #189L; #190L; #191L;
             #192L; #193L; #194L; #195L; #196L; #197L;
             #198L; #199L; #200L |]
  in
  check_i r;
  (* dynamic blocks *)
  let[@inline never] f x = x in
  let r = [| f #0L; f #1L; f #2L; f #3L; f #4L; f #5L;
             f #6L; f #7L; f #8L; f #9L; f #10L; f #11L;
             f #12L; f #13L; f #14L; f #15L; f #16L; f #17L;
             f #18L; f #19L; f #20L; f #21L; f #22L; f #23L;
             f #24L; f #25L; f #26L; f #27L; f #28L; f #29L;
             f #30L; f #31L; f #32L; f #33L; f #34L; f #35L;
             f #36L; f #37L; f #38L; f #39L; f #40L; f #41L;
             f #42L; f #43L; f #44L; f #45L; f #46L; f #47L;
             f #48L; f #49L; f #50L; f #51L; f #52L; f #53L;
             f #54L; f #55L; f #56L; f #57L; f #58L; f #59L;
             f #60L; f #61L; f #62L; f #63L; f #64L; f #65L;
             f #66L; f #67L; f #68L; f #69L; f #70L; f #71L;
             f #72L; f #73L; f #74L; f #75L; f #76L; f #77L;
             f #78L; f #79L; f #80L; f #81L; f #82L; f #83L;
             f #84L; f #85L; f #86L; f #87L; f #88L; f #89L;
             f #90L; f #91L; f #92L; f #93L; f #94L; f #95L;
             f #96L; f #97L; f #98L; f #99L; f #100L; f #101L;
             f #102L; f #103L; f #104L; f #105L; f #106L; f #107L;
             f #108L; f #109L; f #110L; f #111L; f #112L; f #113L;
             f #114L; f #115L; f #116L; f #117L; f #118L; f #119L;
             f #120L; f #121L; f #122L; f #123L; f #124L; f #125L;
             f #126L; f #127L; f #128L; f #129L; f #130L; f #131L;
             f #132L; f #133L; f #134L; f #135L; f #136L; f #137L;
             f #138L; f #139L; f #140L; f #141L; f #142L; f #143L;
             f #144L; f #145L; f #146L; f #147L; f #148L; f #149L;
             f #150L; f #151L; f #152L; f #153L; f #154L; f #155L;
             f #156L; f #157L; f #158L; f #159L; f #160L; f #161L;
             f #162L; f #163L; f #164L; f #165L; f #166L; f #167L;
             f #168L; f #169L; f #170L; f #171L; f #172L; f #173L;
             f #174L; f #175L; f #176L; f #177L; f #178L; f #179L;
             f #180L; f #181L; f #182L; f #183L; f #184L; f #185L;
             f #186L; f #187L; f #188L; f #189L; f #190L; f #191L;
             f #192L; f #193L; f #194L; f #195L; f #196L; f #197L;
             f #198L; f #199L |]
  in
  check_i r;
  let r = [| f #0L; f #1L; f #2L; f #3L; f #4L; f #5L;
             f #6L; f #7L; f #8L; f #9L; f #10L; f #11L;
             f #12L; f #13L; f #14L; f #15L; f #16L; f #17L;
             f #18L; f #19L; f #20L; f #21L; f #22L; f #23L;
             f #24L; f #25L; f #26L; f #27L; f #28L; f #29L;
             f #30L; f #31L; f #32L; f #33L; f #34L; f #35L;
             f #36L; f #37L; f #38L; f #39L; f #40L; f #41L;
             f #42L; f #43L; f #44L; f #45L; f #46L; f #47L;
             f #48L; f #49L; f #50L; f #51L; f #52L; f #53L;
             f #54L; f #55L; f #56L; f #57L; f #58L; f #59L;
             f #60L; f #61L; f #62L; f #63L; f #64L; f #65L;
             f #66L; f #67L; f #68L; f #69L; f #70L; f #71L;
             f #72L; f #73L; f #74L; f #75L; f #76L; f #77L;
             f #78L; f #79L; f #80L; f #81L; f #82L; f #83L;
             f #84L; f #85L; f #86L; f #87L; f #88L; f #89L;
             f #90L; f #91L; f #92L; f #93L; f #94L; f #95L;
             f #96L; f #97L; f #98L; f #99L; f #100L; f #101L;
             f #102L; f #103L; f #104L; f #105L; f #106L; f #107L;
             f #108L; f #109L; f #110L; f #111L; f #112L; f #113L;
             f #114L; f #115L; f #116L; f #117L; f #118L; f #119L;
             f #120L; f #121L; f #122L; f #123L; f #124L; f #125L;
             f #126L; f #127L; f #128L; f #129L; f #130L; f #131L;
             f #132L; f #133L; f #134L; f #135L; f #136L; f #137L;
             f #138L; f #139L; f #140L; f #141L; f #142L; f #143L;
             f #144L; f #145L; f #146L; f #147L; f #148L; f #149L;
             f #150L; f #151L; f #152L; f #153L; f #154L; f #155L;
             f #156L; f #157L; f #158L; f #159L; f #160L; f #161L;
             f #162L; f #163L; f #164L; f #165L; f #166L; f #167L;
             f #168L; f #169L; f #170L; f #171L; f #172L; f #173L;
             f #174L; f #175L; f #176L; f #177L; f #178L; f #179L;
             f #180L; f #181L; f #182L; f #183L; f #184L; f #185L;
             f #186L; f #187L; f #188L; f #189L; f #190L; f #191L;
             f #192L; f #193L; f #194L; f #195L; f #196L; f #197L;
             f #198L; f #199L; f #200L |]
  in
  check_i r;
  check_i [| #0L; ((fun x -> x) #1L)|];
  check_i [| #0L; ((fun x -> x) #1L); #2L|];

  let () =
    let (=) = Int64_u.equal in
    (* match statement *)
    let d = [| #1L; #2L |] in
    (match d with
      | [| a; b |] ->
        assert (a = #1L);
        assert (b = #2L)
      | _ -> assert false);

    (* let statement pattern *)
    let a = [||] in
    let b = [| #1L |] in
    let c = append a b in
    let[@warning "-8"] [| d |] = c in
    assert (d = #1L);

    (* function argument pattern *)
    let[@warning "-8"] f [| b |] = b in
    assert (f [| #1L |] = #1L)
  in
  ()
